version: '3'

services:
  transaction-db:
    container_name: transaction_database
    image: postgres:16.2
    restart: always
    volumes:
    - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transaction_db